import Head from 'next/head'
import styles from '../styles/layout.module.css'
import NavBar from './NavBar'
import React from 'react'
const Layout = ({ children }: { children: React.ReactNode }) => {

  return <div className={styles.container}>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className={styles.header}>
      <NavBar />
      <div className={styles.buttons}>
        <a>Admin</a>
      </div>
    </header>
    <main className={styles.main}>
      {children}
    </main>
    <footer className={styles.footer}>
      <span className={"highlighted"}>&copy; 2021 MiscLG</span>
    </footer>

  </div>
}

export default Layout